// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace timyao.iOS
{
	public partial class moveToMapView : UIViewController
	{
		public moveToMapView (IntPtr handle) : base (handle)
		{
		}
	}
}
